name: Build and run test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.20', '1.21', '1.22', '1.23', '1.24', '1.25' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get ./...
      - name: Run gofmt
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Some files are not correctly formatted. Run 'gofmt -l -w'."
            exit 1
          fi
      - name: Run golangci-lint
        if: matrix.go-version >= '1.22'
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          go-version: ${{ matrix.go-version }}
        env:
          CGO_ENABLED: ${{ matrix.go-version < '1.22' && '0' || '' }}
      - name: Build
        run: go build -v ./...
        env:
          CGO_ENABLED: ${{ matrix.go-version < '1.22' && '0' || '' }}
      - name: Test with Go
        run: go test -json ./... > TestResults-${{ matrix.go-version }}.json
        env:
          CGO_ENABLED: ${{ matrix.go-version < '1.22' && '0' || '' }}
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
